import "./globals.css";
import { Barlow_Condensed } from "next/font/google";

const barlow = Barlow_Condensed({ subsets: ["latin"], weight: ["300"] });

export const metadata = {
  title: "Space Tourism",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={barlow.className}>
      <body>{children}</body>
    </html>
  );
}
